remote_theme: just-the-docs/just-the-docs
title:
description: Solutions to Competitive Programming Problems

color_scheme: light
enable_copy_code_button: true
mermaid:
  version: "11.17.0"

aux_links:
  "Cismaru Eric-Dimitrie": "https://github.com/cdeedc"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red