remote_theme: just-the-docs/just-the-docs
title: Competitive Programming Solutions
description: Solutions for various Competitive Programming Problems

aux_links:
  "MyGitHub": "https://cdeedc_cps.github.io"
